# Generated by Django 5.2.3 on 2025-06-13 12:11

import customauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', customauth.models.UserManager()),
            ],
        ),
    ]
